# Generated by Django 5.2 on 2025-04-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_slug'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TroughUserTag',
            new_name='ThroughUserTag',
        ),
    ]
