# Generated by Django 5.2 on 2025-04-27 07:58

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_troughusertag_throughusertag'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throughusertag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='throughusertag',
            name='tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
        migrations.DeleteModel(
            name='ThroughUserTag',
        ),
    ]
